[workspace]
resolver = "2"

members = ["horo", "api", "horo_date_time"]


[profile.release]
opt-level = 3 # fast and small wasm

# Optimize all dependencies even in debug builds:
[profile.dev.package."*"]
opt-level = 0
